codestates-seb/seb39_main_004

client/src/components/CommonUI/Tag.tsx, client/src/components/Search/SearchBar.tsx, client/src/components/Search/SearchResultList.tsx, client/src/pages/Search/Search.tsx, client/src/styles/GlobalStyle.ts
- 검색 페이지 마크업 및 CSS
- 검색창 컴포넌트
- 추후 인기 태그 클릭 시 해당 키워드로 자동 검색 되도록 구현할 예정입니다.
- 페이지네이션 컴포넌트 만들어지고 하단에 추가할 예정입니다.
=> [FE] 검색 페이지 마크업 및 CSS

client/package-lock.json, client/package.json, client/src/components/CommonUI/Button.tsx, client/src/components/CommonUI/InputWithLabel.tsx, client/src/components/CommonUI/StyledInput.tsx, client/src/components/CommonUI/TextareaWithLabel.tsx, client/src/components/CommonUI/index.ts, client/src/components/Login/LoginForm.tsx, client/src/components/SNSInfo/SNSInfoForm.tsx, client/src/components/SignUp/SignUpForm.tsx
- react-hook-form 라이브러리를 사용하여 로그인 및 회원가입, SNS 회원가입 페이지 유효성 검사 적용하였습니다.
- 기존 inputWithLabel 공용 컴포넌트에 react-hook-form을 적용하려 하였으나, 오류가 발생해 styledInput 컴포넌트를 새로 만들어서 구현하였습니다. 
- 추후 백엔드에서 유효성 검사 기준이 변경되면 수정이 있을 수 있습니다.
- 빌드 후 소스코드 보이지 않게 package.json 빌드 옵션을 변경하였습니다.
- CSS는 로그인 기능 구현 후 진행하도록 하겠습니다.
=> [FE] 로그인 및 회원가입 페이지 유효성 검사 적용

server/src/main/java/run/ward/mmz/dto/respones/RecipeInfoDto.java, server/src/main/java/run/ward/mmz/mapper/post/RecipeMapper.java, server/src/main/java/run/ward/mmz/mapper/post/impl/RecipeMapperImpl.java, server/src/main/java/run/ward/mmz/web/controller/v1/RecipeController.java
=> feat: info Dto 작성 및 response 구현 #31

client/src/App.tsx, client/src/components/RecipeDetail/IngredientItem.tsx, client/src/components/RecipeDetail/Rating.tsx, client/src/components/RecipeDetail/RecipeInfo.tsx, client/src/components/RecipeDetail/RecipeStep.tsx, client/src/components/RecipeDetail/RepleContainer.tsx, client/src/components/RecipeDetail/RepleList.tsx, client/src/components/RecipeDetail/RepleUpload.tsx, client/src/components/RecipeDetail/UserInfo.tsx, client/src/pages/Recipe/PostDetail.tsx, client/src/pages/Recipe/data.ts
- 유저컴포넌트
- 레시피정보 컴포넌트(카테고리,재료)
- 레시피 순서 컴포넌트
- 댓글 컴포넌트
- 별점 컴포넌트
- CSS 및 레이아웃은 디자인 픽스되면 변경될 수 있습니다.
=> [FE]게시글 조회 페이지 마크업

server/src/main/java/run/ward/mmz/domain/post/Recipe.java, server/src/main/java/run/ward/mmz/dto/request/patch/RecipePatchDto.java, server/src/main/java/run/ward/mmz/dto/request/post/RecipePostDto.java, server/src/main/java/run/ward/mmz/dto/respones/RecipeResponseDto.java, server/src/main/java/run/ward/mmz/mapper/post/impl/RecipeMapperImpl.java, server/src/main/java/run/ward/mmz/repository/RecipeRepository.java, server/src/main/java/run/ward/mmz/repository/ReviewRepository.java, server/src/main/java/run/ward/mmz/service/ReviewService.java, server/src/main/java/run/ward/mmz/service/impl/ReviewServiceImpl.java, server/src/main/java/run/ward/mmz/web/controller/v1/RecipeController.java, server/src/main/java/run/ward/mmz/web/controller/v1/ReviewController.java, server/src/main/java/run/ward/mmz/web/controller/v1/TestController.java
=> feat : 레시피 level 삭제 및 프론트 데이터 확인 #31

server/src/main/java/run/ward/mmz/web/config/WebMvcConfig.java
=> feat : cors 설정 #31

server/src/main/java/run/ward/mmz/domain/post/Tag.java, server/src/main/java/run/ward/mmz/service/impl/RecipeServiceImpl.java, server/src/main/java/run/ward/mmz/service/impl/RecipeTagServiceImpl.java
=> feat : 검색기능 오류 수정 #31

server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
=> feat : cors 변경 #83

server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java, server/src/main/java/run/ward/mmz/web/config/WebMvcConfig.java
=> feat : cors 에러 변경.. #83

server/src/main/java/run/ward/mmz/handler/auth/LoginSuccessHandler.java
=> feat : 핸들러 페이지 추가 #83

server/src/main/java/run/ward/mmz/handler/auth/CustomLogoutSuccessHandler.java
- 로그아웃 핸들러가 서비스등록이 안되어있던 버그 수정
-
=> feat : 로그아웃 service di추가 #83

server/src/main/java/run/ward/mmz/dto/request/post/patch/RecipePatchDto.java, server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
- 인텔리제이에서는 오류나지 않는 내용이 server에서는 발생
- 401에러 확인을 위한 pull request
-
=> feat : recipe patch dto -> response dto 변경  #93

server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
=> feat : 프론트엔드 요청으로 인한, 권한 삭제 get Recipe edit page #93

server/src/main/java/run/ward/mmz/domain/account/Account.java, server/src/main/java/run/ward/mmz/dto/common/ResponseDto.java, server/src/main/java/run/ward/mmz/dto/respones/ReviewResponseDto.java, server/src/main/java/run/ward/mmz/dto/respones/UserPageDto.java, server/src/main/java/run/ward/mmz/mapper/post/impl/ReviewMapperImpl.java, server/src/main/java/run/ward/mmz/repository/post/RecipeRepository.java, server/src/main/java/run/ward/mmz/service/account/AccountService.java, server/src/main/java/run/ward/mmz/service/account/impl/AccountServiceImpl.java, server/src/main/java/run/ward/mmz/service/account/impl/SubscribeServiceImpl.java, server/src/main/java/run/ward/mmz/service/post/BookmarkService.java, server/src/main/java/run/ward/mmz/service/post/RecipeService.java, server/src/main/java/run/ward/mmz/service/post/impl/BookmarkServiceImpl.java, server/src/main/java/run/ward/mmz/service/post/impl/RecipeServiceImpl.java, server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java, server/src/main/java/run/ward/mmz/web/controller/v1/account/SubscribeController.java, server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java, server/src/main/java/run/ward/mmz/web/controller/v1/post/ReviewController.java
- 레시피 상세페이지 로그인 안해도 볼 수 있도록 변경
- 유저 페이지 작성글, 리뷰, 팔로워, 북마크 리스트 기능 추가
- 유저 프로필 사진 업데이트 기능 추가
-
=> Feat/be/121 user page 업데이트

server/src/main/java/run/ward/mmz/domain/post/Recipe.java, server/src/main/java/run/ward/mmz/handler/auth/CustomLoginFailureHandler.java, server/src/main/java/run/ward/mmz/handler/exception/ExceptionCode.java, server/src/main/java/run/ward/mmz/handler/exception/GlobalExceptionHandler.java, server/src/main/java/run/ward/mmz/service/post/impl/BookmarkServiceImpl.java, server/src/main/java/run/ward/mmz/web/config/SecurityConfig.java
- 북마크 권한오류 해결
- 로그인 실패 시 에러 변경 테스트
-
=> https 환경에서 로그인 / 로그아웃 정상적으로 동작하지않는 에러 테스트

client/src/components/NewRecipe/IngredientsSet.tsx, client/src/components/NewRecipe/RecipeFormStyled.ts, client/src/components/NewRecipe/StepSet.tsx, client/src/components/NewRecipe/buttons/RemoveBtn.tsx
- 레시피 추가 페이지 요리재료,요리순서 레이아웃 수정
=> [FE] 레시피 추가 페이지 레이아웃 수정

server/src/main/java/run/ward/mmz/domain/account/Account.java, server/src/main/java/run/ward/mmz/domain/post/Bookmark.java, server/src/main/java/run/ward/mmz/dto/respones/AccountInfoDto.java, server/src/main/java/run/ward/mmz/dto/respones/RecipeInfoDto.java, server/src/main/java/run/ward/mmz/handler/auth/LoginUser.java, server/src/main/java/run/ward/mmz/repository/post/BookmarkRepository.java, server/src/main/java/run/ward/mmz/service/auth/OAuth2UserService.java, server/src/main/java/run/ward/mmz/service/post/BookmarkService.java, server/src/main/java/run/ward/mmz/service/post/impl/BookmarkServiceImpl.java, server/src/main/java/run/ward/mmz/web/config/SwqggerConfig.java, server/src/main/java/run/ward/mmz/web/controller/v1/account/AccountController.java, server/src/main/java/run/ward/mmz/web/controller/v1/post/RecipeController.java
- 북마크 버그 수정 및 전체 게시판에서 북마크 확인 기능을 추가하였습니다.
-
=> feat : 전체 리스트 북마크 여부 확인 추가

client/src/components/Main/RecipeItem/RecipeItem.tsx
- 비회원 북마크 시 토스트 메시지 뜨지 않는 문제 해결
=> [FE] 비회원 북마크 시 토스트 메시지 뜨지 않는 문제 해결

client/src/components/CommonUI/Footer.tsx, client/src/components/CommonUI/Header.tsx, client/src/components/CommonUI/SortButtons.tsx, client/src/components/CommonUI/Tag.tsx, client/src/components/Layout.tsx, client/src/components/Main/Category/RecipeCategory.tsx, client/src/components/Main/RecipeItem/RecipeItem.tsx, client/src/components/Main/RecipeItem/RecipeItemList.tsx, client/src/components/Search/SearchBar.tsx, client/src/components/Search/SearchResultList.tsx, client/src/index.tsx, client/src/pages/Main/Main.tsx, client/src/pages/Mypage/MyPage.tsx, client/src/pages/Mypage/MyPageBookMark/MyPageBookMark.tsx, client/src/pages/Mypage/MyPageRecipe/MyPageRecipe.tsx, client/src/pages/Mypage/MyPageUser/MyPageUser.tsx, client/src/pages/Search/Search.tsx, client/src/styles/Theme.ts
- 헤더,푸터, 메인 페이지,검색 페이지,마이페이지 반응형 구현
- 다른페이지는 풀리퀘 후 추가작업 예정입니다.
=> [FE] 반응형 웹페이지 구현

client/src/components/RecipeDetail/UserInfo.tsx, client/src/pages/Recipe/PostDetail.tsx, client/src/types/interface.ts
=> [FE] 레시피 페이지 id 중복으로 인한 버그 해결

client/src/components/Login/LoginForm.tsx, client/src/components/Login/SNSLogin.tsx, client/src/components/RecipeDetail/UserInfo.tsx, client/src/redux/slices/userSlice.ts
- 세션 체크 시 토스트 메시지 삭제
- 로그인 하지 않았는데 내 게시글 수정 및 삭제 버튼이 노출되는 버그 해결
- 카카오 로그인 URL 연결
=> [FE] 버그 해결 및 카카로 로그인 URL 연결

client/src/components/NewRecipe/ThumbNailUploader.tsx, client/src/components/RecipeDetail/UserInfo.tsx, client/src/pages/Recipe/EditPost.tsx
- 수정페이지에서 썸네일 수정이 안되었던 에러 수정
수정페이지 접근을 위해 UserInfo 컴포넌트에 잠시 주석처리 했습니다.
=> [FE] 수정페이지 썸네일 오류 수정

client/src/pages/Main/Main.tsx
=> [FE] 카테고리 버그 1차 픽스 테스트 풀리퀘

client/src/pages/Main/Main.tsx
=> [FE] 사용하지 않는 코드 삭제

client/src/components/Main/RecipeItem/RecipeItemList.tsx, client/src/pages/Mypage/MyPageBookMark/MyPageBookMark.tsx, client/src/pages/Mypage/MyPageRecipe/MyPageRecipe.tsx, client/src/pages/Mypage/MyPageReview/MyPageReview.tsx, client/src/types/interface.ts
=> (FE) 마이페이지 시간데이터 초단위 제거(#192)

client/src/components/RecipeDetail/RepleList.tsx
- 로그인 하지 않았을 때 후기 페이지 렌더링 되지 않는 버그를 해결하였습니다.
=> fix: 로그인 하지 않았을 때 후기 페이지 렌더링 되지 않는 버그 해결 (#197)
